integration_tests/e2e/applications.cy.ts
integration_tests/fixtures/sections.json

This PR;
Adds integrations tests and fixtures - `applications.cy.ts`
https://dsdmoj.atlassian.net/browse/RA-222

RA-222: add integrations tests

---

integration_tests/e2e/applications.cy.ts
server/constants/applicationTypes.ts
server/routes/applications/index.ts
server/services/auditService.ts
server/views/pages/applications.njk
server/views/pages/log/application-type.njk

This PR;
Creates the log application type route.
Adds placeholder `application-type.njk` template.
https://dsdmoj.atlassian.net/browse/RA-213

RA-213: create log application type route

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Adding COMPONENT_API_URL config for frontend components api from the doc
[RA-234](https://dsdmoj.atlassian.net/browse/RA-235)
[RA-234]: https://dsdmoj.atlassian.net/browse/RA-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding frontend components api config

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

A small fix - Adding the missing quotes
[RA-235](https://dsdmoj.atlassian.net/browse/RA-235)
[RA-235]: https://dsdmoj.atlassian.net/browse/RA-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding the missing quotes

---

server/constants/applicationTypes.ts
server/routes/applications/index.ts
server/views/pages/log/application-type.njk

[RA-216](https://dsdmoj.atlassian.net/browse/RA-216)
[RA-216]: https://dsdmoj.atlassian.net/browse/RA-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Application types page template

---

integration_tests/e2e/application-type.cy.ts
integration_tests/fixtures/applicationTypes.json

[RA-216](https://dsdmoj.atlassian.net/browse/RA-216)
[RA-216]: https://dsdmoj.atlassian.net/browse/RA-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding integration tests for application type page

---

server/views/pages/view-application/swap-visiting-orders-for-pin-credit.njk

This PR;
Creates the foundational template to be used for the `Swap visiting orders (VOs) for PIN credit` view.
NB: values to be added from API
https://dsdmoj.atlassian.net/browse/RA-264

RA-264: create view application njk template

---

server/views/pages/submit-application/swap-visiting-orders-for-pin-credit.njk

Created submit application template for Swap VOs for PIN credit page
[RA-226](https://dsdmoj.atlassian.net/browse/RA-226)
[RA-226]: https://dsdmoj.atlassian.net/browse/RA-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-257-swap-vos-application-submit-template

---

integration_tests/e2e/submit-swap-visiting-orders-for-pin-credit-application.cy.ts
integration_tests/pages/submitSwapVosPinCreditApplicationPage.ts
server/views/pages/submit-application/swap-visiting-orders-for-pin-credit.njk

[RA-258](https://dsdmoj.atlassian.net/browse/RA-258)
- Tests for submission page - swap VOs for PIN credit page
- Also added navigation links 
[RA-258]: https://dsdmoj.atlassian.net/browse/RA-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature/RA-258 added tests for submit swap vos application page + navigation links

---

integration_tests/e2e/action-and-reply.cy.ts
integration_tests/pages/actionAndReply.ts

https://dsdmoj.atlassian.net/browse/RA-297

RA-297: add closed app test cases

---

integration_tests/e2e/action-and-reply.cy.ts
integration_tests/e2e/application-history.ts
integration_tests/e2e/comments.cy.ts
integration_tests/e2e/confirm-details.cy.ts
integration_tests/e2e/forward-application.cy.ts
integration_tests/e2e/submit-application.cy.ts
integration_tests/e2e/view-application.cy.ts
integration_tests/mockApis/managingPrisonerApps.ts
server/@types/managingAppsApi.ts
server/data/managingPrisonerAppsClient.test.ts
server/data/managingPrisonerAppsClient.ts
server/routes/applications/forwardApplicationRoutes.ts
server/routes/applications/viewApplicationsRoutes.ts
server/routes/testutils/testData.ts
server/routes/validate/validateForwardingApplication.test.ts
server/routes/validate/validateForwardingApplication.ts
server/services/managingPrisonerAppsService.test.ts
server/services/managingPrisonerAppsService.ts
server/views/pages/applications/forward/swap-visiting-orders-for-pin-credit.njk
server/views/pages/applications/view/swap-visiting-orders-for-pin-credit.njk

This PR;
Implements the forward application api endpoint
Cleans up tests
https://dsdmoj.atlassian.net/browse/RA-314

RA-314: api functionality

---

server/routes/applications/index.ts
server/routes/applications/viewApplicationsRoutes.ts
server/utils/formatAppsToRows.ts
server/views/pages/applications/list/index.njk

https://dsdmoj.atlassian.net/browse/RA-304

RA-304: update pending apps tab implementation

---

server/utils/formatAppsToRows.ts

PR for the Closed tab view
[RA-306](https://dsdmoj.atlassian.net/browse/RA-306)
[RA-306]: https://dsdmoj.atlassian.net/browse/RA-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding Closed tab view

---

server/routes/applications/viewApplicationsRoutes.ts
server/utils/nunjucksSetup.ts
server/utils/pagination.test.ts
server/utils/pagination.ts
server/views/pages/applications/list/index.njk

[RA-308](https://dsdmoj.atlassian.net/browse/RA-308)
Implement pagination handling for Pending and Closed tabs
[RA-308]: https://dsdmoj.atlassian.net/browse/RA-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-308/add pagination for pending and closed tabs

---

server/views/pages/applications/list/index.njk

[RA-308](https://dsdmoj.atlassian.net/browse/RA-308)
A small  fix to adding pagination inside the tabs for Pending and Closed one
[RA-308]: https://dsdmoj.atlassian.net/browse/RA-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

A small fix - pagination sits inside the tab

---

assets/scss/application.scss
package-lock.json
package.json
server/@types/managingAppsApi.ts
server/data/managingPrisonerAppsClient.ts
server/middleware/setUpStaticResources.ts
server/routes/applications/viewApplicationsRoutes.ts
server/services/managingPrisonerAppsService.ts
server/utils/filters.ts
server/views/components/accessibleAutocomplete/macro.njk
server/views/pages/applications/list/partials/filter.njk
server/views/partials/layout.njk

This PR;
Implements the prisoner search filter.
https://dsdmoj.atlassian.net/browse/RA-309

RA-309: prisoner search filter

---

server/routes/applications/viewApplicationsRoutes.ts
server/views/pages/applications/list/index.njk

Adding error summary on top
https://dsdmoj.atlassian.net/browse/RA-312

Adding the error summary

---

package-lock.json
package.json

Upgrade @ministryofjustice/frontend to v5.1.0
[RA-340](https://dsdmoj.atlassian.net/browse/RA-340)
[RA-340]: https://dsdmoj.atlassian.net/browse/RA-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update MoJ Frontend

---

integration_tests/e2e/action-and-reply.cy.ts
integration_tests/mockApis/managingPrisonerApps.ts
server/@types/managingAppsApi.ts
server/data/managingPrisonerAppsClient.test.ts
server/data/managingPrisonerAppsClient.ts
server/routes/applications/actionAndReplyRoutes.ts
server/routes/applications/viewApplicationsRoutes.ts
server/routes/testutils/testData.ts
server/services/managingPrisonerAppsService.test.ts
server/services/managingPrisonerAppsService.ts
server/views/pages/applications/action/closed.njk
server/views/pages/applications/action/pending.njk
server/views/pages/applications/comments/index.njk

https://dsdmoj.atlassian.net/browse/RA-291

RA-291: app response api implementation

---

integration_tests/e2e/forward-application.cy.ts
integration_tests/pages/forwardApplicationPage.ts
server/routes/applications/forwardApplicationRoutes.ts
server/views/pages/applications/forward/index.njk

Forward page UI for add emergency pin phone credit apptype with tests
[RA-319](https://dsdmoj.atlassian.net/browse/RA-319)
[RA-319]: https://dsdmoj.atlassian.net/browse/RA-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature/RA-319: forward emergency pin phone credit UI

---

integration_tests/e2e/action-and-reply.cy.ts
server/routes/applications/actionAndReplyRoutes.ts
server/routes/validate/validateActionAndReply.test.ts
server/routes/validate/validateActionAndReply.ts
server/views/pages/applications/action/index.njk
server/views/pages/applications/action/pending.njk

[RA-322](https://dsdmoj.atlassian.net/browse/RA-322)
[RA-322]: https://dsdmoj.atlassian.net/browse/RA-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-322: Action and reply emergency pin phone credit

---

assets/scss/views/_applications.scss
server/@types/managingAppsApi.ts
server/routes/applications/viewApplicationsRoutes.ts
server/routes/testutils/testData.ts

Fixing the **From** column in the view apps apge to correctly display the firstname and lastname and also TestData
Also made some CSS addition to match the prototype

Fixing From column data display on view apps page

---

integration_tests/e2e/prisoner-details.cy.ts
integration_tests/fixtures/applicationTypes.json
integration_tests/pages/logPrisonerDetails.ts
integration_tests/tsconfig.json
server/constants/applicationTypes.ts

https://dsdmoj.atlassian.net/browse/RA-362
Adding the app type _Supply list of PIN phone contacts_, displaying it on the next page Prisoner details - and adding relevant tests

RA-362: Adding supply list pin contacts app type

---

integration_tests/e2e/application-details.cy.ts
integration_tests/fixtures/applicationTypes.json
server/@types/express/index.d.ts
server/routes/applications/applicationDetailsRoutes.ts
server/routes/applications/commentsRoutes.ts
server/routes/validate/validateTextField.test.ts
server/routes/validate/validateTextField.ts
server/utils/getAppTypeLogDetails.ts
server/utils/handleAppDetails.ts
server/views/pages/log-application/application-details/partials/supply-list-of-pin-phone-contacts.njk

[RA-361](https://dsdmoj.atlassian.net/browse/RA-361)
Log details page for the app type **Supply list of PIN phone contacts**
UI + Refactored the code, applicationDetailsRoutes.ts, validateTextFiled.ts
Refactored the tests
[RA-361]: https://dsdmoj.atlassian.net/browse/RA-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-361: Log details supply list page

---

server/views/pages/log-application/confirm/partials/supply-list-of-pin-phone-contacts.njk

https://dsdmoj.atlassian.net/browse/RA-363

RA-363: add app type request details

---

integration_tests/e2e/forward-application.cy.ts
integration_tests/pages/forwardApplicationPage.ts

https://dsdmoj.atlassian.net/browse/RA-366
This PR includes the refactoring of the Forward app tests, and the UI is working as expected for _Supply list of PIN phone contacts_ app type

RA-366: Refactoring forward app tests

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-staging.yaml
integration_tests/e2e/view-application.cy.ts
integration_tests/pages/viewApplicationPage.ts
server/config.ts
server/routes/applications/viewApplicationsRoutes.ts
server/views/pages/applications/view/index.njk
server/views/pages/applications/view/partials/supply-list-of-pin-phone-contacts.njk

This PR covers all the ACs listed for this ticket and  includes refactored tests.
[RA-365 ](https://dsdmoj.atlassian.net/browse/RA-365)

RA-365: View application page

---

assets/scss/views/_applications.scss
server/app.ts
server/views/pages/applications/action/index.njk
server/views/pages/applications/comments/index.njk
server/views/pages/applications/forward/index.njk
server/views/pages/applications/history/index.njk
server/views/pages/applications/list/index.njk
server/views/pages/applications/view/index.njk

https://dsdmoj.atlassian.net/browse/RA-407

RA-407: breadcrumbs

---

integration_tests/e2e/application-type.cy.ts
server/routes/applications/applicationTypeRoutes.ts

[RA-426](https://dsdmoj.atlassian.net/browse/RA-426)
Update error message to 'Choose one application type' and fixed relevant tests
[RA-426]: https://dsdmoj.atlassian.net/browse/RA-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update text for snag 5

---

server/routes/validate/validateAmountField.test.ts
server/routes/validate/validateAmountField.ts
server/views/pages/applications/change/partials/add-emergency-pin-phone-credit.njk
server/views/pages/log-application/application-details/partials/add-emergency-pin-phone-credit.njk

[RA-423](https://dsdmoj.atlassian.net/browse/RA-423)
Update text, remove a validation check and relevant tests for snag-2.
[RA-423]: https://dsdmoj.atlassian.net/browse/RA-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-423: Snag-2

---

server/views/components/pagination/macro.njk
server/views/pages/applications/list/partials/closed.njk
server/views/pages/applications/list/partials/pending.njk

https://dsdmoj.atlassian.net/browse/RA-450

RA-450: update pagination

---

integration_tests/e2e/view-application.cy.ts
integration_tests/pages/viewApplicationPage.ts
server/views/pages/applications/view/index.njk

View profile and View alerts link to be open in a new tab
https://dsdmoj.atlassian.net/browse/RA-457

Links opening in new tabs

---

helm_deploy/values-dev.yaml

This PR is part of [RA-408](https://dsdmoj.atlassian.net/browse/RA-408)
[RA-412](https://dsdmoj.atlassian.net/browse/RA-412)
Updating DEV environment url.
[RA-408]: https://dsdmoj.atlassian.net/browse/RA-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RA-412]: https://dsdmoj.atlassian.net/browse/RA-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-412: update dev url

---

helm_deploy/values-preprod.yaml

Subtask for [RA-408](https://dsdmoj.atlassian.net/browse/RA-408)
[RA-412](https://dsdmoj.atlassian.net/browse/RA-412)
Updating PREPROD environment URL
[RA-408]: https://dsdmoj.atlassian.net/browse/RA-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RA-412]: https://dsdmoj.atlassian.net/browse/RA-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-412: updating preprod url

---

server/routes/applications/actionAndReplyRoutes.ts

https://dsdmoj.atlassian.net/browse/RA-466

RA-466: update redirect

---

assets/js/index.js
integration_tests/e2e/application-details.cy.ts
integration_tests/e2e/confirm-details.cy.ts
integration_tests/e2e/prisoner-details.cy.ts
server/routes/applications/prisonerDetailsRoutes.ts
server/views/pages/log-application/prisoner-details/index.njk

"Find prisoner" button validation on Log Prisoner details page and relevant tests
[RA-451](https://dsdmoj.atlassian.net/browse/RA-451)
[RA-451]: https://dsdmoj.atlassian.net/browse/RA-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-451: Button validation

---

server/app.ts
server/data/managingPrisonerAppsClient.test.ts
server/data/managingPrisonerAppsClient.ts
server/middleware/setUpHealthChecks.ts
server/services/managingPrisonerAppsService.test.ts
server/services/managingPrisonerAppsService.ts
server/views/partials/layout.njk

https://dsdmoj.atlassian.net/browse/RA-427

RA-427: add active agencies to info endpoint

---

server/routes/index.test.ts
server/routes/index.ts
server/routes/static-pages/staticPagesRoutes.ts
server/views/pages/static-pages/accessibility-statement.njk

Adding accessibility statement
https://dsdmoj.atlassian.net/browse/RA-470

RA-470: Adding-accessibility-statement-page

---

server/views/pages/applications.njk

PR to add feedback link
[RA-341](https://dsdmoj.atlassian.net/browse/RA-341)
[RA-341]: https://dsdmoj.atlassian.net/browse/RA-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-341: Add feedback link

---

server/views/pages/applications/list/partials/filter.njk

PR to update text
[RA-503](https://dsdmoj.atlassian.net/browse/RA-503)
[RA-503]: https://dsdmoj.atlassian.net/browse/RA-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RA-503: update text

---

server/views/pages/static-pages/accessibility-statement.njk

https://dsdmoj.atlassian.net/browse/RA-505

RA-505: small text amends

---

integration_tests/e2e/application-details.cy.ts
integration_tests/e2e/view-application.cy.ts
integration_tests/fixtures/applicationTypes.json
server/@types/express/index.d.ts
server/constants/applicationTypes.ts
server/routes/applications/prisonerDetailsRoutes.ts
server/routes/validate/validatePrisonerDetails.test.ts
server/routes/validate/validatePrisonerDetails.ts
server/views/pages/log-application/prisoner-details/index.njk

https://dsdmoj.atlassian.net/browse/RA-192

RA-192: add social pin phone contact app type

---

server/routes/validate/validatePrisonerDetails.test.ts
server/routes/validate/validatePrisonerDetails.ts

Updated error message to match Figma design

A minor error message update

---

integration_tests/e2e/prisoner-details.cy.ts
integration_tests/pages/logPrisonerDetails.ts
server/views/pages/log-application/prisoner-details/index.njk

Add cypress tests for radio button field in Log prisoner details page 
and a minor spacing fix

Add e2e test for radio button field log prisoner details

---

server/views/pages/log-application/application-details/partials/add-social-pin-phone-contact.njk

https://dsdmoj.atlassian.net/browse/RA-528

RA-528: update copy

---

server/@types/managingAppsApi.ts
server/routes/applications/changeApplicationRoutes.ts
server/routes/testutils/testData.ts
server/utils/getAppDetails.ts
server/views/pages/applications/change/index.njk
server/views/pages/applications/change/partials/add-social-pin-phone-contact.njk
server/views/pages/applications/change/partials/errors.njk

PR for the "Change" feature allowing log details to be edited - Add new social pin phone app type
https://dsdmoj.atlassian.net/browse/RA-199
All acceptance criteria (ACs) have been covered.
When the user clicks "Change" from View page, they are taken to the Log Details page with all fields prefilled.
Clicking "Continue" takes them to the Check details page.
Upon clicking the "Save" button, they are shown a confirmation message:
"Application submitted: Add new social PIN phone contact."

RA-199: Change functionality for social contact log details

---

server/views/pages/applications/change/partials/add-social-pin-phone-contact.njk

Reflecting the same changes on Change log details page
https://dsdmoj.atlassian.net/browse/RA-528

Update text in Change log details page

---

server/views/pages/log-application/confirm/partials/application-details.njk

https://dsdmoj.atlassian.net/browse/RA-535

RA-535: update copy

---

assets/js/index.js
server/@types/express/index.d.ts
server/routes/applications/prisonerDetailsRoutes.ts
server/views/pages/log-application/prisoner-details/index.njk

https://dsdmoj.atlassian.net/browse/RA-543

RA-543: fix validation + js cleanup

---

integration_tests/pages/confirmDetailsPage.ts
integration_tests/pages/viewApplicationPage.ts
server/views/pages/applications/view/partials/application-details.njk

Changed label from 'Date sent' to 'Date'. Also removed unused variables from test files.
https://dsdmoj.atlassian.net/browse/RA-601

RA-601- A small text change

---

integration_tests/e2e/application-details.cy.ts
integration_tests/e2e/prisoner-details.cy.ts
integration_tests/pages/applicationDetailsPage.ts
integration_tests/pages/logPrisonerDetails.ts
server/@types/express/index.d.ts
server/routes/applications/prisonerDetailsRoutes.ts
server/routes/validate/validateNewSocialPinPhoneContact.test.ts
server/routes/validate/validateNewSocialPinPhoneContact.ts
server/routes/validate/validatePrisonerDetails.test.ts
server/routes/validate/validatePrisonerDetails.ts
server/utils/handleAppDetails.ts
server/views/pages/applications/view/partials/add-social-pin-phone-contact.njk
server/views/pages/applications/view/partials/application-details.njk
server/views/pages/log-application/application-details/partials/add-social-pin-phone-contact.njk
server/views/pages/log-application/application-details/partials/errors.njk
server/views/pages/log-application/confirm/partials/add-social-pin-phone-contact.njk
server/views/pages/log-application/confirm/partials/application-details.njk
server/views/pages/log-application/prisoner-details/index.njk

https://dsdmoj.atlassian.net/browse/RA-544

RA-544: move early days centre question to app details

---

assets/scss/views/_applications.scss
server/utils/getValidApplicationOrRedirect.ts
server/views/pages/error.njk

Also updated the styling of the error page.

More graceful handling of application type unknown errors

---

server/views/pages/applications/change/partials/add-legal-pin-phone-contact.njk

https://dsdmoj.atlassian.net/browse/RA-421

RA-421: add change app details view

---

server/routes/applications/viewApplicationsRoutes.ts

https://dsdmoj.atlassian.net/browse/RA-659
This PR removes the count display from Application type filters when filters are applied.

RA-659: Remove count from Application type filter display

---

server/data/managingPrisonerAppsClient.test.ts
server/data/managingPrisonerAppsClient.ts
server/routes/applications/changeApplicationRoutes.ts
server/services/managingPrisonerAppsService.test.ts
server/services/managingPrisonerAppsService.ts
server/utils/formatEarlyDaysCentre.ts
server/views/pages/applications/change/partials/add-social-pin-phone-contact.njk
server/views/pages/applications/list/partials/filter.njk

https://dsdmoj.atlassian.net/browse/RA-612
Ability to modify the response to the first night centre question for submitted applications and updated relevant tests
Also a small text change on the filter page

RA-656: Edit first night centre value

---

integration_tests/e2e/view-application.cy.ts
integration_tests/fixtures/applicationTypes.json
server/@types/express/index.d.ts
server/constants/applicationTypes.ts
server/routes/applications/applicationDetailsRoutes.ts
server/routes/testutils/testData.ts
server/routes/validate/validateNewOfficialContact.ts
server/utils/apps.test.ts
server/utils/getAppDetails.ts
server/utils/getAppTypeLogDetails.ts
server/utils/handleAppDetails.ts
server/views/pages/applications/change/partials/add-official-pin-phone-contact.njk
server/views/pages/applications/view/partials/add-official-pin-phone-contact.njk
server/views/pages/log-application/application-details/partials/add-official-pin-phone-contact.njk
server/views/pages/log-application/confirm/partials/add-official-pin-phone-contact.njk

https://dsdmoj.atlassian.net/browse/RA-657

RA-657: change legal to official
